name: 'Get Blockchain info'

on:
  workflow_dispatch:
    inputs:
      networkName:
        description: 'Enter the network name'
        required: true
        type: string
      clusterAlias:
        description: 'Enter the name of your cluster'
        required: true
        type: string
      n:
        description: "No of loops"
        required: true
        type: string
        default: "10"
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  getBlockchainInfo:
    name: 'Listing blockchain info in loop until timeout'
    runs-on: ubuntu-latest
    #in order to make input.timeout usable as timeout-minutes we need this strategy workaround
    environment: production
    
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Set env variables
        run: |
          echo "REGION_FILE_PATH=./private/${{ github.event.inputs.networkName }}/${{ github.event.inputs.clusterAlias }}/region" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
          
      - name: Read region
        run: |
          echo "REGION=$(cat $REGION_FILE_PATH)" >> $GITHUB_ENV
          
      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_GH_ACTIONS_ROLE }}
          aws-region: ${{env.REGION}}
          
      - name: Connect to cluster
        run: |
            aws eks --region ${{env.REGION}} update-kubeconfig --name ${{ github.event.inputs.clusterAlias }}

      - name: Install kubectl 
        uses: azure/setup-kubectl@v3
        
      - name: Create the status script
        run: |
          cat > status.sh << EOF
          function isSynced() {
            if [[ "$1"=="false" ]]
            then
            	echo "synced"
            else  
            	echo "syncing..."
            fi
          }

          for i in {1..${{ inputs.n }}};
          do
              quorumPodName="$(kubectl get pods --selector=app.kubernetes.io/name=quorum --no-headers -o custom-columns="POD-NAME":.metadata.name)"
              echo \$quorumPodName
              numberOfBlocks=\$(kubectl exec -t \$quorumPodName -c quorum -- sh -c "./geth-helpers/geth-exec.sh 'eth.blockNumber'")
              lastBlockHash=\$(kubectl exec -t \$quorumPodName -c quorum -- sh -c "./geth-helpers/geth-exec.sh 'eth.getBlock(eth.blockNumber).hash'")
              nodeIsSync=\$(kubectl exec -t \$quorumPodName -c quorum -- sh -c "./geth-helpers/geth-exec.sh 'eth.syncing'")
          
              echo number of mined blocks \$numberOfBlocks
              echo hash of last block \$numberOfBlocks
              echo Node is \$(isSynced $nodeIsSync)
          done
          EOF 
      - name: Set permissions
        run: chmod 755 status.sh
        
      - name: Retrieve information in loop
        run: ./status.sh
